version: "3.7"
services:
    database:
        image: mysql:latest
        container_name: database
        command: mysqld --sql_mode=""
        volumes:
            - ./database/dump:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: kalla
            MYSQL_PASSWORD: kalla123456
            MYSQL_DATABASE: kalla
            TZ: Asia/Makassar
        ports:
            - "3306:3306"
        networks:
            - laravel-network
    phpmyadmin:
        depends_on:
            - database
        image: phpmyadmin:latest
        container_name: phpmyadmin
        restart: always
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: kalla
            MYSQL_PASSWORD: kalla123456
        ports:
            - 8080:80
        networks:
            - laravel-network
networks:
    laravel-network:
        driver: bridge
